### ISSUE TITLE
[1.18.2] Make disabling passive heaters optional

### ISSUE THREAD

**Issue by V972** [zehmaria/createlowheated#4]
Full transparency -- while I can see the appeal, I'm not that interested in the vision of yours of making Create more restricted.    
I installed this mod solely for the basic burner and more granularity that it brings to the [un]heated recipes scale (which is amazing).

But apparently I can't f-ing read XD    
because I thought that's all the mod does and only yesterday found out that it also disables passive boiler heaters (in favor of basic burner)

So...can you please make it optional in the config (and enabled by default obviously)?

**Comment by zehmaria** [comment]
Idk how you missed it, it is literally everywhere, I am baffled.  

Well, I can do a config for you, but as a consequence it will fully disable the Basic Burner ability to heat the steam engine. 

Using that config option: 

- The passive stuff for the steam engine will come back, and the Basic Burner will be unable to heat it. 
- Only the recipe stuff will remain for the Basic Burner as a consequence. 
- So the tooltip in the block must be changed via altering the lang file on your end, if the inaccuracy bothers you.

**Comment by V972** [comment]
Idk how I missed it either, but...yeah. No one to blame but myself ¯\\\_(ツ)_/¯

It's not critical for me to lose basic burner passive heating (I am using it for recipes after all), but if it's not too hard/long, can you please explain why it would need to be disabled instead of still providing passive level of heat (I know it will be kinda redundant gameplay-wise, but I assume you mean the need is technical)?    
For context, I do programming for a living so not totally unfamiliar with things), but little idea how MC modding (and create specifically) works.

As for the tooltip, I guess I can I fix it w/ KubeJS, but for others it may be more critical. Why can't it depend on config as well (which iirc requires restart anyway)?

Thank you in advance, thanks for considetring my request in the first place and using this opportunity, special thanks for still updating 1.18!

**Comment by V972** [comment]
Oh I almost forgot.    
I wonder if I need to make this as a separate issue, but I'd really love Jade compatibility to show remaining item burn time akin to blaze burner.        
<details><summary>Click to open</summary>     

![image](https://github.com/zehmaria/createlowheated/assets/45125685/cc08070b-f54b-4094-b1c6-ae08b573a5f7) 
</details>

<details><summary>Click to open</summary>     

![image](https://github.com/zehmaria/createlowheated/assets/45125685/c75c39c6-7ed9-4e31-b567-4dac5182ad92)
</details>

**Comment by zehmaria** [comment]
The thing about disabling, it was just easier. It could be done, but I don't want to bother. Even more because it would be so pointless to have both. Why bother using the Basic Burner and waste fuel instead of placing down a campfire? Thematically, it just doesn't make sense, so why spend a little extra time thinking and coding that little bit. And after thinking more about it, it is kind of sad for the poor thing to generate the same speed, why treat it like that, better to have a clean distinction. 

The thing about tooltips is because of how Create handles tooltips. And my tooltip uses their system. It adds them via language entries, they can then be changed via language entries, to easily support community supported translations. It is not hard coded in each block related classes, where I can plop a if case and be done. Idk if that conditional tool-tip can even be done without implementing something else on my own either, haven't looked too deep on it, but it doesn't seem trivial. And since changing it via language entries is trivial, but doing it in code is not, I will leave it to anyone that wants to cut that feature off to deal with it. 

That is how far as I am willing to go. If it is trivial, I don't mind implementing an option to disable something like that, but I won't spend hours and hours looking at how to do something like that. 

I also noticed the jade thingy, and I even looked into it, but I couldn't figure it out. If I ever get to understand how to do it, I will implement it. But my experience with all this is limited, I only know so much and I couldn't do it so far, so I will leave it like that for now. 

The new version is ready and tested a bit, the change doesn't seem to have broken anything, so I will be uploading it to the sites now. It will be there in a bit, once the respective sites process the file.

**Comment by V972** [comment]
:O    
That was fast!    
Thank you so much!    
Downloaded and tested, everything seems to work.

I see your point about disabling and tooltip, like I said I accept it and I have KubeJS to fix the tooltip.    
A bit of a shame about Jade, but oh well, it's not _that_ critical, since I can at least see the items quantity.
