### ISSUE TITLE
Activator takes the coal

### ISSUE THREAD

**Issue by Mapter322** [zehmaria/createlowheated#7]
The activator takes coal from the main burner instead of putting it into it

**Comment by zehmaria** [comment]
Which activator? I am not sure which block you are talking about, but I will explain insert/extraction in general. 

So, the burner is basically a depot/basin with a filter, so stuff can be inserted and taken. So, any form of insertion needs to be one way in, or else you will find it behaving like that. If the "block/entity" can insert and remove stuff, it might even do both at the same time, but look like it has done nothing. 

The basic burner does not behave like the blaze burner, where it eats up whatever you put into it [disappears]. Instead, the basic burner has an inventory and such and can even drop items once broken. 

When using Create stuff, you can insert coal with a funnel. But you can also remove coal with it, if used in the extraction mode. The same applies to mechanical arms. And in the case of the deployer, it can insert, but if the fake hand is empty, it will remove, following the same logical behavior that the player hands follow. I've tested it to a good point, and find the logic consistent, however it doesn't really act exactly like anything else tho, so that might cause confusion. 

Tbf, Item-insertion-wise, the basic burner is more closely related to the depot/basin than the blaze burner. You can even Q-drop stuff into it. 

Hope this explains. If you still thinks there is something wrong, explain it in more details.

**Comment by Mapter322** [comment]
Okay, I got it, thank you. And yes, I meant deployer, it's just called differently in my translation)))
